#!/bin/sh

trap 'printf "\e[0m"' DEBUG

# PROMPT_COMMAND='pc=$?; wd=$(pwd | wc -m); printf "\e[s\e[1;$(expr $COLUMNS - ${wd} + 1)f$(for n in $(seq 1 ${wd});do printf " ";done)\e[${wd}D\e[1m$(pwd)\e[0m\n\e[$(expr $COLUMNS - 11)C$(LANG=en_US.UTF-8 date +"%a %b %d")\n\e[$(expr $COLUMNS - 6)C$(TZ="Asia/Tokyo" date +"%H:%M")\e[u"; wd=$(pwd | wc -m)'

# "\e[?25l" => hides the cursor.
# 'WD_COL_NUM=$(PWD | wc =m);' => working directory columns number.
# '\e[s' => save cursor position.
# '\e[<n>;<m>f' => horizontal and vertical position. == <n>;<m>H
# '\e[<n>D' => cursor back.
# '\e[<n>C' => cursor forward.
# '\e[u' => restore cursor position.
# "\e[25h" => shows the cursor.

echo_cat() {
    local ret
    for tmp in $*
    do
	ret+=$tmp
    done
    echo -n $ret
}

export pc

PROMPT_COMMAND=$(echo -n \
	'pc=$?;' \
	'printf "\033[?25l";' \
	'WD_COL_NUM=$(pwd | wc -m);' \
	'printf' \
	$(IFS=$'\n'; echo_cat $(for i in \
		'"' \
		'\033[s' \
		'\033[1;$(($COLUMNS-${WD_COL_NUM}+1))f' \
		'$(for n in $(seq 1 ${WD_COL_NUM});' \
		'do ' \
			'echo -n '"'"' '"'"';' \
		'done)' \
		'\033[${WD_COL_NUM}D' \
		'\033[1m${PWD}\e[0m\n' \
		'\033[$(($COLUMNS-11))C' \
		'$(LANG=en_US.UTF-8 date +'"'"'%a %b %d'"'"')\n' \
		'\033[$(($COLUMNS-6))C' \
		'$(TZ=Asia/Tokyo date +'"'"'%H:%M'"'"')' \
		'\033[u' \
		'"' \
		';'
		do
			echo $i
		done
	)) \
	'printf "\033[?25h"' \
)

PS1='\[\e[0m\]$pc $SHLVL $(if [ $pc -eq 0 ]; then echo "\[\e[0;32m\];)"; else echo "\[\e[0;31m\]:("; fi) \[\e[38;5;248m\]\W \[\e[0;$([ $HOME == "/root" ] && echo "31" || echo "34")m\]\$ \[\e[38;5;248m\]'
PS2='>> '

flasher() {
    while true
    do
	printf "\e[?5h"
	sleep 0.1
	printf "\e[?5l"
	read -s -n1 -t1 && break
    done
}


colors() {
    local fgc bgc vals seq0

    printf "Color escapes are %s\n" '\e[${value};...;${value}m'
    printf "Values 30..37 are \e[33mforeground colors\e[m\n"
    printf "Values 40..47 are \e[43mbackground colors\e[m\n"
    printf "Value  1 gives a  \e[1mbold-faced look\e[m\n\n"

    # foreground colors
    for fgc in {30..37}; do
	# background colors
	for bgc in {40..47}; do
	    fgc=${fgc#37} # white
	    bgc=${bgc#40} # black

	    vals="${fgc:+$fgc;}${bgc}"
	    vals=${vals%%;}

	    seq0="${vals:+\e[${vals}m}"
	    printf "  %-9s" "${seq0:-(default)}"
	    printf " ${seq0}TEXT\e[m"
	    printf " \e[${vals:+${vals+$vals;}}1mBOLD\e[m"
	done
	echo; echo
    done
}

colors256() {
  local i j k
  printf "\n"
  for i in {0..27}
  do
      printf " "
  done
  printf "\033[1m\\\033[38;5;\033[4m%%d\033[0;1mm"
  printf "\033[G"
  printf "\033[%dC" $((3+16*4+2))
  for i in {0..27}
  do
      printf " "
  done
  printf "\\\033[48;5;\033[4m%%d\033[0;1mm\n\n\033[0m"
  
  printf "   "
  for i in {0..15}
  do
    printf " %X  " $i      
  done
  printf "     "
  for i in {0..15}
  do
    printf " %X  " $i      
  done
  printf "\n"

  for i in {0..15}
  do
      printf " %X " $i

      for j in {0..15}
      do
	  k=$(($i*16+$j))
	  printf "\033[38;5;%dm%03d " $k $k
      done
      printf "  "

      printf " \033[0m%X " $i
      for j in {0..15}
      do
	  k=$(($i*16+$j))
	  printf "\033[48;5;%dm%03d" $k $k
	  printf "\033[0m "
      done
      printf "\n\n"

  done
  
  printf "\033[0m "
}

colors_all() {
    local h i j k t w LorS
    SorL=$(( $COLUMNS < 144 ))
    echo; echo

    t='SGR (Select Graphic Rendition) parameters'
    w=$(echo -n "$t" | wc -m)
    printf "\033[%dC" $(( ((140-$SorL*70)-$w)/2 ))
    printf "\033[1m"; echo $t; echo; printf "\033[0m"    

    for i in 0 5
    do
	    for j in {0..4}
	    do
	        k=$(( $j + $i ))
    	    printf "\033[%dm%14d" $k $k
    	    printf "\033[0m"
	    done
	    [ $SorL == 1 ] && [ $i == 0 ] && echo
    done
    echo
    for h in {0..4}
    do
             for i in 0 10
             do
	             for j in {0..9}
	             do
	                 k=$(( $i + $j + 10 + h*20))
	                 #printf "%7s" ""
	                 printf "\033[%dm%7d" $k $k
	                 printf "\033[0m"
	             done
	             [ $SorL == 1 ] && [ $i == 0 ] && echo
             done
             echo
    done
    echo; echo
    
    t='256-color mode'
    w=$(echo -n $t | wc -m)
    printf "\033[%dC" $(( ((144-$SorL*72)-$w)/2 ))
    printf "\033[1m"; echo $t;
    t='foreground: ESC[38;5;#m  background: ESC[48;5;#m'
    w=$(echo -n "$t" | wc -m)
    printf "\033[%dC" $(( ((144-$SorL*72)-$w)/2 ))
    echo "$t"; echo; printf "\033[0m"

    t='Standard colors'
    w=$(echo -n $t | wc -m)
    printf "\033[%dC" $(( ((72-$SorL*36)*(1+$SorL)-$w)/2 ))
    echo -n $t; printf "\033[%dC" $(( (72-$SorL*36)*(1+$SorL) - ((72-$SorL*36)*(1+$SorL)-$w)/2 - $w ))
    echo
    i=0
	[[ $i != 0 ]] && printf "\033[0m" && printf "\033[30m" ||  printf "\033[1m"
	for j in {0..7}
	do
	    k=$(( $i + $j ))
	    printf "\033[48;5;%dm%9d" $k $k
	done
    printf "\033[0m"
            if [ $SorL == 1 ]; then
                echo
            else
                printf "\033[s"
                printf "\033[A"
            fi
            t='High-intensity colors'
            w=$(echo -n $t | wc -m)
            printf "\033[%dC" $(( ((72-$SorL*36)*(1+$SorL)-$w)/2 ))
            echo -n $t
            if [ $SorL == 1 ]; then
                echo
            else
                printf "\033[u"
            fi
            i=8
            [[ $i != 0 ]] && printf "\033[0m" && printf "\033[30m" ||  printf "\033[1m"
	        for j in {0..7}
	        do
	            k=$(( $i + $j ))
	            printf "\033[48;5;%dm%9d" $k $k
	        done
            printf "\033[0m\n"

    t='216 colors'
    w=$(echo -n $t | wc -m)
    printf "\033[%dC" $(( ((144-$SorL*72)-$w)/2 ))
    echo $t
    for h in {0..5}
    do
        i=0
	    [[ $i != 0 ]] && printf "\033[0m" && printf "\033[30m" ||  printf "\033[1m"
	    for j in {0..17}
	    do
		    k=$(( $i + $j + 36*$h + 16 ))
		    printf "\033[48;5;%dm%4d" $k $k
	    done
	    printf "\033[0m"
        [ $h != 5 ] && printf "\n"
    done
            if [ $SorL == 1 ]; then
                echo; echo; echo; echo; echo; echo
            fi
            printf "\033[5A"
            for h in {0..5}
            do
                i=18
	            [[ $i != 0 ]] && printf "\033[30m" ||  printf "\033[1m"
                printf "\033[s"
	            for j in {0..17}
	            do
		            k=$(( $i + $j + 36*$h + 16 ))
		            printf "\033[48;5;%dm%4d" $k $k
	            done
	            printf "\033[u\033[B"
            done
            printf "\033[G\033[0m"
            echo
            
    t='Grayscale colors'
    w=$(echo -n "$t" | wc -m)
    printf "\033[%dC" $(( ((144-$SorL*72)-$w)/2 ))
    echo "$t"
    for i in 0 12
    do
	    [[ $i != 0 ]] && printf "\033[0m" && printf "\033[30m" ||  printf "\033[1m"
	    for j in {0..11}
	    do
	        k=$(( $i + $j + 232 ))
	        printf "\033[48;5;%dm%6d" $k $k
	    done
        [ $SorL == 1 ] && [ $i == 0 ] && echo -e "\e[0m"
    done
    printf "\033[0m\n"

    echo; echo
}
