# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
export TZ=Asia/Tokyo
export PYTHONPATH="$HOME/python/modules"

# ハッシュテーブルにコマンド追加
shopt -s failglob # ワイルドカード展開(bash)
. ~/.bash_aliases
. ~/sh/prompt.sh

